= CSoftZ Tech And Solve Lazy Problem Test

V1.0.1 - Mar.30/2017

*Created:* Mar.24/2017 {zwsp} +
*Modified:* Mar.30/2017 {zwsp} +

This project is a solution to the problem Lazy worker problem.
With a little research the problem is a *_Facebook Hacker Cup 2017 Qualification Round_*

https://www.facebook.com/hackercup/problem/169401886867367/

Besides the last link, there other few links that offer a solution to the problem.
They are listed as follows:
. https://github.com/ruippeixotog/facebook-hacker-cup-2017/blob/master/qualification/lazy-loading.cpp the
solution here is in CPP (C++)
. https://github.com/flacode/lazy_loading/blob/master/fb.py the solution here is in Python.
  

== Technology used
In the intent of selecting the best technology for the realization of the problem, the
following is a list of frameworks, libraries used.

* Java 8
* Spring Framework to ease the creation of Enterprise grade Java Applications.
* Spring Boot to ease the configuration of the many  java libraries out there in the Java ecosystem. The version
used is V1.5.2 (via maven transitivity dependency resolution, it selects the appropriate Spring Framework verson).
* Apache Cassandra to make a repository for Registration objects. Version used V3.10
* The abstraction to access the repository uses Spring Data with Cassandra support.

